/*
 * This source file was generated by the Gradle 'init' task
 */
package httpservaah;
import java.io.*;
import java.net.*;
import java.io.*;
import java.net.*;

public class MyServer {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
            ServerSocket s = new ServerSocket(8080);
            System.out.println("Started servert at port 8080.....");

            Socket socket = s.accept();
            System.out.println("Connected to client..");

            InputStream inputStream = socket.getInputStream();
            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(inputStream));
            String msg;
            while ((msg = bufferedReader.readLine()) != null && !msg.isEmpty()) {
                System.out.println(msg);
            }

            InputStream input = MyServer.class.getResourceAsStream("/index.html");
            BufferedReader bufferedReaderhtml = new BufferedReader(new InputStreamReader(input));
            
            StringBuilder sb = new StringBuilder();
            String line;

            while ((line = bufferedReaderhtml.readLine()) != null) {
                sb.append(line).append("\n");
            }
            String htmlPage = sb.toString();


            BufferedWriter bufferedWriter = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream()));
            BufferedWriter out = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream()));
            out.write("HTTP/1.1 200 OK\r\n");
            out.write("Content-Type: text/html\r\n");
            out.write("\r\n");
            out.write(htmlPage);
            out.flush();

            socket.close();
            s.close();
            }
        catch (IOException e){
                e.printStackTrace();
            }

        }
}

